# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
en:
  languageCode: en-US
  locale: en-US
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/en
  weight: 1
  timeZone: America/New_York
ru:
  languageCode: ru-RU
  locale: ru-RU
  contentDir: content/ru
  weight: 2
  title: Денис Трофимов
  timeZone: Europe/Moscow
# Uncomment the lines below to configure your website in a second language.
#zh:
#  languageCode: zh-Hans
#  contentDir: content/zh
#  title: Chinese website title...
#  params:
#    description: Site description in Chinese...
#  menu:
#    main:
#      - name: 传
#        url: '#about'
#        weight: 1
